name: build

on:
  push:
    branches:
      - '*'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: mymindstorm/setup-emsdk@v11
      - name: Create Build Environment
        shell: bash
        working-directory: ${{runner.workspace}}
        run: cmake -E make_directory build
      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: |
          emcmake cmake "$GITHUB_WORKSPACE" -DCMAKE_BUILD_TYPE=Release
      - name: Build
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake --build . --config "$BUILD_TYPE" -j 2
          echo "export default Module;" >> sfizz.wasm.js
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sfizz-webaudio
          path: |
            index.html
            index.js
            index.css
            sfizz-node.js
            sfizz-processor.js
            ${{runner.workspace}}/build/sfizz-wasm.js
            util/WASMAudioBuffer.js

upload:
  name: Create release and upload artifacts
  needs:
    - build_for_linux
  runs-on: ubuntu-latest
  steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
    - name: Inspect directory
      run: ls -alFR
    - name: Create release and upload artifacts
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          wget -q https://github.com/TheAssassin/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage
          chmod +x pyuploadtool-x86_64.AppImage
          ./pyuploadtool-x86_64.AppImage sfizz-webaudio.zip